name: test-and-deploy
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: npm i
      - name: Run Test
        run: npm run test
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/dev/ChessServer
          git pull origin master
          git status
          npm i
          npm run build
          sudo cp -pf ./build/index.js /data/modules
          sudo systemctl daemon-reload
          sudo systemctl restart nakama