name: test-and-deploy
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "21.x"
      - name: Install dependencies
        run: npm i
      - name: Run Test
        run: npm run test
    